### PR TITLE
test: Fix threading issues in SenderThreadSpec

### LINKED ISSUE #31: Replace `Thread#sleep` in test cases
There's a bunch of unit tests that relies on `Thread#sleep` which makes them inherently flaky.
Let's try to make those tests more robust with stuff like [awaitility](https://github.com/awaitility/awaitility) or [`CountDownLatch`](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/CountDownLatch.html)

### PR DESCRIPTION
**Pull request by corycaywood**
# Description 
Fixes #31.

Replaced usages of Thread#sleep with Awaitility or Mockito#timeout. Additionally, fixed an issue where the populateBufferRunnable was not terminated after being used, so it would cause NullPointerException sometimes. Previously, some of these unit tests were failing occasionally on CI.

The only other place where `Thread#sleep` is used is in `TrackerImplSpec`, however these appear to be valid uses because it's being used to test metric start and end times.

## Links
#31 

# Checklist
- [x] I have read the [contributing guidelines](../CONTRIBUTING.md).
- [x] I wrote/updated tests for new/changed code
- [x] I ran `./gradlew check` without errors

### CODE REVIEW

File: Core/src/test/java/com/rakuten/tech/mobile/perf/core/SenderThreadSpec.java [hunk 1]
```diff
@@ -71,60 +70,40 @@ public void uncaughtException(Thread t, Throwable e) {
...
-      doReturn(0).when(sender).send(anyInt());
-      loop(senderThread, 1); // give it some time to finish run()
-
-      Thread.sleep(50);
-
-      verify(sender, atLeast(4)).send(anyInt());
-    }
-
-
-    @Test public void shouldResetFailureCountAfterSuccess()
```
Comment (corycaywood) [inline Core/src/test/java/com/rakuten/tech/mobile/perf/core/SenderThreadSpec.java:110]: I removed this test because it looked to me like it wasn't actually testing anything at all, unless I misunderstood something?

Also, `shouldResetFailureCountAfterSuccess ` sounds like it's supposed to test exactly the same thing as the above test `shouldResetBackOffAfterSuccess`.

File: Core/src/test/java/com/rakuten/tech/mobile/perf/core/SenderThreadSpec.java [hunk 2]
```diff
@@ -71,60 +70,40 @@ public void uncaughtException(Thread t, Throwable e) {
           fail("uncaught exception");
         }
       });
-      senderThread.start();
-      Thread.sleep(100);
-      senderThread.terminate();
-      loop(senderThread, 1);
+      startSenderThread(senderThread);
+
+      verify(sender, timeout(50).atLeast(1)).send(anyInt());
```
Comment (NemoOudeis) [inline Core/src/test/java/com/rakuten/tech/mobile/perf/core/SenderThreadSpec.java:75]: nice, i didn't know about that

**Review by NemoOudeis — APPROVED** [review]
